# Generated by Django 4.2.6 on 2023-10-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistgenerator', '0002_alter_album_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', related_query_name='album', to='playlistgenerator.artist'),
        ),
    ]
