# Generated by Django 4.2.6 on 2023-10-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistgenerator', '0003_alter_album_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
