# Generated by Django 4.2.6 on 2023-10-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistgenerator', '0004_item_amount'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='playlistgen_content_3a0760_idx',
        ),
        migrations.RemoveField(
            model_name='item',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='object_id',
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('ARTIST', 'Artist'), ('ALBUM', 'Album')], default='ALBUM', max_length=16, null=True),
        ),
    ]
