# Generated by Django 4.2.6 on 2023-10-05 22:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('playlistgenerator', '0006_playlist_item_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='playlist',
        ),
        migrations.AddField(
            model_name='item',
            name='albums',
            field=models.ManyToManyField(related_name='albums_set', related_query_name='album', to='playlistgenerator.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='artists',
            field=models.ManyToManyField(related_name='artists_set', related_query_name='artist', to='playlistgenerator.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.AddField(
            model_name='playlistrow',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='playlistgenerator.item'),
        ),
        migrations.AddField(
            model_name='playlistrow',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', related_query_name='row', to='playlistgenerator.playlist'),
        ),
    ]
