# Generated by Django 4.2.6 on 2023-10-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistgenerator', '0007_playlistrow_remove_item_amount_remove_item_playlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='albums_set', related_query_name='album', to='playlistgenerator.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='artists_set', related_query_name='artist', to='playlistgenerator.item'),
        ),
    ]
