# Generated by Django 4.2.6 on 2023-10-05 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlistgenerator', '0008_alter_item_albums_alter_item_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='albums',
        ),
    ]
